In [51]:
import numpy as np

In [52]:
a=[1,2,3,4,5,6]
b=[i**2 for i in a]
print(b)

[1, 4, 9, 16, 25, 36]


In [53]:
a=np.array([1,2,3,4,5,6])
a**2

array([ 1,  4,  9, 16, 25, 36])

In [54]:
type(a)

numpy.ndarray

In [55]:
a.dtype

dtype('int64')

In [56]:
a=range(10000)

In [57]:
%timeit [i**2 for i in a]

4.25 ms ± 325 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [58]:
b=np.arange(10000)

In [59]:
%timeit b**2

8.64 µs ± 739 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [60]:
a=range(0,10)

In [61]:
a

range(0, 10)

In [62]:
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [63]:
b=np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [64]:
b**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [65]:
b.ndim

1

In [66]:
b.shape

(10,)

In [67]:
# np.linspace(start,stop,count)
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [68]:
a=np.array([[1,2,3],[11,22,33]])

In [69]:
a

array([[ 1,  2,  3],
       [11, 22, 33]])

In [70]:
a.ndim

2

In [71]:
a.shape

(2, 3)

In [72]:
a.dtype

dtype('int64')

In [73]:
type(a)

numpy.ndarray

In [74]:
a=np.arange(1,13)

In [75]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
a.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [77]:
a.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [78]:
a.reshape(-1,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [79]:
b=a.reshape(6,-1)
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [80]:
b.T

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [81]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [83]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [85]:
b=np.arange(1,13).reshape(-1,6)
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [86]:
c=b.reshape(3,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [89]:
a[0:5]

array([1, 2, 3, 4, 5])

In [93]:
a[5:11]

array([ 6,  7,  8,  9, 10, 11])

In [1]:
import numpy as np

In [2]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
a[0]

array([1, 2, 3, 4])

In [5]:
a[0,:]

array([1, 2, 3, 4])

In [6]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
a=a.reshape(4,3)

In [10]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
a[1:3,:2]

array([[4, 5],
       [7, 8]])

In [13]:
a[[0,1,3],:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [16]:
a[(0,1,3),:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [17]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
a[::-2,::-2]

array([[12, 10],
       [ 6,  4]])

In [19]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
a<6

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [21]:
mask=a<6
print(mask)

[[ True  True  True]
 [ True  True False]
 [False False False]
 [False False False]]


In [22]:
a[mask]

array([1, 2, 3, 4, 5])

In [23]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [25]:
a=np.arange(11,16)
b=np.arange(1,6)
print(a)
print(b)

[11 12 13 14 15]
[1 2 3 4 5]


In [26]:
a+b

array([12, 14, 16, 18, 20])

In [27]:
a=np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [28]:
np.sum(a)

465

In [29]:
np.sum(a,axis=0)

array([ 81,  87,  93,  99, 105])

In [30]:
np.sum(a,axis=1)

array([ 15,  40,  65,  90, 115, 140])

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [33]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [39]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [44]:
a=np.array([4,3,2,1])
b=np.array([4,3,2,4])

In [47]:
a<b

array([False, False, False,  True])

In [45]:
np.any(a<b)

True

In [46]:
np.all(a<b)

False

In [1]:
import numpy as np

In [2]:
a=np.array([4,2,65,56,0,6,9])
a

array([ 4,  2, 65, 56,  0,  6,  9])

In [3]:
np.sort(a)

array([ 0,  2,  4,  6,  9, 56, 65])

In [ ]:
a

In [2]:
import numpy as np
a=np.array([4,2,65,56,0,6,9])
a

array([ 4,  2, 65, 56,  0,  6,  9])

In [3]:
a

array([ 4,  2, 65, 56,  0,  6,  9])

In [4]:
np.sort(a)

array([ 0,  2,  4,  6,  9, 56, 65])

In [5]:
a.sort()

In [6]:
a

array([ 0,  2,  4,  6,  9, 56, 65])

In [9]:
a=np.array([[23,2,54],[17,3,42],[15,5,65]])
a

array([[23,  2, 54],
       [17,  3, 42],
       [15,  5, 65]])

In [10]:
np.sort(a)

array([[ 2, 23, 54],
       [ 3, 17, 42],
       [ 5, 15, 65]])

In [12]:
np.sort(a,axis=1)

array([[ 2, 23, 54],
       [ 3, 17, 42],
       [ 5, 15, 65]])

In [15]:
np.sort(a,axis=0)

array([[15,  2, 42],
       [17,  3, 54],
       [23,  5, 65]])

In [14]:
a

array([[23,  2, 54],
       [17,  3, 42],
       [15,  5, 65]])

In [16]:
np.argsort(a)

array([[1, 0, 2],
       [1, 0, 2],
       [1, 0, 2]])

In [17]:
np.argsort(a,axis=0)

array([[2, 0, 1],
       [1, 1, 0],
       [0, 2, 2]])

In [18]:
np.argsort(a,axis=1)

array([[1, 0, 2],
       [1, 0, 2],
       [1, 0, 2]])

In [19]:
ls

Data Via conti..ipynb              Pandas_Revision.ipynb
Data Viz with seaborn.ipynb        Pfizer_1.csv
MatplotLib conti. + Seaborn.ipynb  directors.csv
Matplotlib.ipynb                   figure.png
Matplotlib_Revision.ipynb          gapminder.csv
Netflix project.ipynb              jupyterthemes.ipynb
Pandas_4.ipynb                     movies.csv
Pandas_5.ipynb                     numpy_pandas_revision.ipynb
Pandas_Rev_conti.ipynb


In [21]:
data=np.loadtxt("https://drive.google.com/file/d/15CRGPBDbg_CQDuKYZbywV0BgMhD8mPmp/view?usp=share_link",dtype="str")

ValueError: Wrong number of columns at line 2