In [51]:
import numpy as np

In [52]:
a=[1,2,3,4,5,6]
b=[i**2 for i in a]
print(b)

[1, 4, 9, 16, 25, 36]


In [53]:
a=np.array([1,2,3,4,5,6])
a**2

array([ 1,  4,  9, 16, 25, 36])

In [54]:
type(a)

numpy.ndarray

In [55]:
a.dtype

dtype('int64')

In [56]:
a=range(10000)

In [57]:
%timeit [i**2 for i in a]

4.25 ms ± 325 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [58]:
b=np.arange(10000)

In [59]:
%timeit b**2

8.64 µs ± 739 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [60]:
a=range(0,10)

In [61]:
a

range(0, 10)

In [62]:
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [63]:
b=np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [64]:
b**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [65]:
b.ndim

1

In [66]:
b.shape

(10,)

In [67]:
# np.linspace(start,stop,count)
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [68]:
a=np.array([[1,2,3],[11,22,33]])

In [69]:
a

array([[ 1,  2,  3],
       [11, 22, 33]])

In [70]:
a.ndim

2

In [71]:
a.shape

(2, 3)

In [72]:
a.dtype

dtype('int64')

In [73]:
type(a)

numpy.ndarray

In [74]:
a=np.arange(1,13)

In [75]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
a.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [77]:
a.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [78]:
a.reshape(-1,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [79]:
b=a.reshape(6,-1)
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [80]:
b.T

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [81]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [83]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [85]:
b=np.arange(1,13).reshape(-1,6)
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [86]:
c=b.reshape(3,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [89]:
a[0:5]

array([1, 2, 3, 4, 5])

In [93]:
a[5:11]

array([ 6,  7,  8,  9, 10, 11])

In [1]:
import numpy as np

In [2]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
a[0]

array([1, 2, 3, 4])

In [5]:
a[0,:]

array([1, 2, 3, 4])

In [6]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
a=a.reshape(4,3)

In [10]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
a[1:3,:2]

array([[4, 5],
       [7, 8]])

In [13]:
a[[0,1,3],:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [16]:
a[(0,1,3),:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [17]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
a[::-2,::-2]

array([[12, 10],
       [ 6,  4]])

In [19]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
a<6

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [21]:
mask=a<6
print(mask)

[[ True  True  True]
 [ True  True False]
 [False False False]
 [False False False]]


In [22]:
a[mask]

array([1, 2, 3, 4, 5])

In [23]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [25]:
a=np.arange(11,16)
b=np.arange(1,6)
print(a)
print(b)

[11 12 13 14 15]
[1 2 3 4 5]


In [26]:
a+b

array([12, 14, 16, 18, 20])

In [27]:
a=np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [28]:
np.sum(a)

465

In [29]:
np.sum(a,axis=0)

array([ 81,  87,  93,  99, 105])

In [30]:
np.sum(a,axis=1)

array([ 15,  40,  65,  90, 115, 140])

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [33]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [39]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [44]:
a=np.array([4,3,2,1])
b=np.array([4,3,2,4])

In [47]:
a<b

array([False, False, False,  True])

In [45]:
np.any(a<b)

True

In [46]:
np.all(a<b)

False

In [1]:
import numpy as np

In [2]:
a=np.array([4,2,65,56,0,6,9])
a

array([ 4,  2, 65, 56,  0,  6,  9])

In [3]:
np.sort(a)

array([ 0,  2,  4,  6,  9, 56, 65])

In [ ]:
a

In [2]:
import numpy as np
a=np.array([4,2,65,56,0,6,9])
a

array([ 4,  2, 65, 56,  0,  6,  9])

In [3]:
a

array([ 4,  2, 65, 56,  0,  6,  9])

In [4]:
np.sort(a)

array([ 0,  2,  4,  6,  9, 56, 65])

In [5]:
a.sort()

In [6]:
a

array([ 0,  2,  4,  6,  9, 56, 65])

In [9]:
a=np.array([[23,2,54],[17,3,42],[15,5,65]])
a

array([[23,  2, 54],
       [17,  3, 42],
       [15,  5, 65]])

In [10]:
np.sort(a)

array([[ 2, 23, 54],
       [ 3, 17, 42],
       [ 5, 15, 65]])

In [12]:
np.sort(a,axis=1)

array([[ 2, 23, 54],
       [ 3, 17, 42],
       [ 5, 15, 65]])

In [15]:
np.sort(a,axis=0)

array([[15,  2, 42],
       [17,  3, 54],
       [23,  5, 65]])

In [14]:
a

array([[23,  2, 54],
       [17,  3, 42],
       [15,  5, 65]])

In [16]:
np.argsort(a)

array([[1, 0, 2],
       [1, 0, 2],
       [1, 0, 2]])

In [17]:
np.argsort(a,axis=0)

array([[2, 0, 1],
       [1, 1, 0],
       [0, 2, 2]])

In [18]:
np.argsort(a,axis=1)

array([[1, 0, 2],
       [1, 0, 2],
       [1, 0, 2]])

In [19]:
ls

Data Via conti..ipynb              Pandas_Revision.ipynb
Data Viz with seaborn.ipynb        Pfizer_1.csv
MatplotLib conti. + Seaborn.ipynb  directors.csv
Matplotlib.ipynb                   figure.png
Matplotlib_Revision.ipynb          gapminder.csv
Netflix project.ipynb              jupyterthemes.ipynb
Pandas_4.ipynb                     movies.csv
Pandas_5.ipynb                     numpy_pandas_revision.ipynb
Pandas_Rev_conti.ipynb


In [33]:
a=np.arange(1,13).reshape(3,4)
b=np.arange(11,23).reshape(4,3)
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [28]:
a*b

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171, 200, 231, 264]])

In [30]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
np.matmul(a,b)

array([[170, 180, 190],
       [418, 444, 470],
       [666, 708, 750]])

In [35]:
np.dot(a,b)

array([[170, 180, 190],
       [418, 444, 470],
       [666, 708, 750]])

In [36]:
a.shape

(3, 4)

In [37]:
b.shape

(4, 3)

In [38]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
np.tile(a,(2,3))

array([[ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12]])

Pandas

In [40]:
ls

Data Via conti..ipynb              Pfizer_1.csv
Data Viz with seaborn.ipynb        Probability Day 1.ipynb
MatplotLib conti. + Seaborn.ipynb  directors.csv
Matplotlib.ipynb                   drive.google.com/
Matplotlib_Revision.ipynb          figure.png
Netflix project.ipynb              gapminder.csv
Pandas_4.ipynb                     jupyterthemes.ipynb
Pandas_5.ipynb                     movies.csv
Pandas_Rev_conti.ipynb             numpy_pandas_revision.ipynb
Pandas_Revision.ipynb              prob_01_basic_definitions/


In [41]:
import pandas as pd

In [42]:
df=pd.read_csv("gapminder.csv")

In [43]:
df

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [44]:
type(df)

pandas.core.frame.DataFrame

In [45]:
df["country"]

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...     
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [46]:
type(df["country"])

pandas.core.series.Series

In [47]:
type(df[["country"]])

pandas.core.frame.DataFrame

In [48]:
df[["country","year"]]

country  year
0     Afghanistan  1952
1     Afghanistan  1957
2     Afghanistan  1962
3     Afghanistan  1967
4     Afghanistan  1972
...           ...   ...
1699     Zimbabwe  1987
1700     Zimbabwe  1992
1701     Zimbabwe  1997
1702     Zimbabwe  2002
1703     Zimbabwe  2007

[1704 rows x 2 columns]

In [49]:
df.head(2)

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030

In [50]:
df.tail(2)

country  year  population continent  life_exp     gdp_cap
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [51]:
df.tail(-10)

country  year  population continent  life_exp      gdp_cap
10    Afghanistan  2002    25268405      Asia    42.129   726.734055
11    Afghanistan  2007    31889923      Asia    43.828   974.580338
12        Albania  1952     1282697    Europe    55.230  1601.056136
13        Albania  1957     1476505    Europe    59.280  1942.284244
14        Albania  1962     1728137    Europe    64.820  2312.888958
...           ...   ...         ...       ...       ...          ...
1699     Zimbabwe  1987     9216418    Africa    62.351   706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377   693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809   792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989   672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487   469.709298

[1694 rows x 6 columns]

In [52]:
df.shape

(1704, 6)

In [53]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [54]:
df.keys()

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [55]:
pd.DataFrame(["Zimbabwe",2007,12311143,"Africa",43.487,469.709298])

0
0    Zimbabwe
1        2007
2    12311143
3      Africa
4      43.487
5  469.709298

In [58]:
pd.DataFrame([["Zimbabwe",2006,12311143,"Africa",43.487,469.709298],
            ["Zimbabwe",2007,12311143,"Africa",43.487,469.709298]])

0     1         2       3       4           5
0  Zimbabwe  2006  12311143  Africa  43.487  469.709298
1  Zimbabwe  2007  12311143  Africa  43.487  469.709298

In [59]:
pd.DataFrame([["Zimbabwe",2006,12311143,"Africa",43.487,469.709298],
            ["Zimbabwe",2007,12311143,"Africa",43.487,469.709298]],
            columns=["country","year","population","continent","life_exp","gdp_cap"])

country  year  population continent  life_exp     gdp_cap
0  Zimbabwe  2006    12311143    Africa    43.487  469.709298
1  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [60]:
pd.DataFrame({"country":["India","Dubai"],
             "year":[2000,2001],
             "population":[1000,2000]})

country  year  population
0   India  2000        1000
1   Dubai  2001        2000

In [61]:
df["country"].head()

0    Afghanistan
1    Afghanistan
2    Afghanistan
3    Afghanistan
4    Afghanistan
Name: country, dtype: object

In [63]:
df[["country","year"]].head()

country  year
0  Afghanistan  1952
1  Afghanistan  1957
2  Afghanistan  1962
3  Afghanistan  1967
4  Afghanistan  1972

In [64]:
df["country"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Leba

In [65]:
df["country"].nunique()

142

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   country     1704 non-null   object 
 1   year        1704 non-null   int64  
 2   population  1704 non-null   int64  
 3   continent   1704 non-null   object 
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [67]:
df.describe()

year    population     life_exp        gdp_cap
count  1704.00000  1.704000e+03  1704.000000    1704.000000
mean   1979.50000  2.960121e+07    59.474439    7215.327081
std      17.26533  1.061579e+08    12.917107    9857.454543
min    1952.00000  6.001100e+04    23.599000     241.165876
25%    1965.75000  2.793664e+06    48.198000    1202.060309
50%    1979.50000  7.023596e+06    60.712500    3531.846988
75%    1993.25000  1.958522e+07    70.845500    9325.462346
max    2007.00000  1.318683e+09    82.603000  113523.132900

In [68]:
df.describe(include="all")

country        year    population continent     life_exp  \
count          1704  1704.00000  1.704000e+03      1704  1704.000000   
unique          142         NaN           NaN         5          NaN   
top     Afghanistan         NaN           NaN    Africa          NaN   
freq             12         NaN           NaN       624          NaN   
mean            NaN  1979.50000  2.960121e+07       NaN    59.474439   
std             NaN    17.26533  1.061579e+08       NaN    12.917107   
min             NaN  1952.00000  6.001100e+04       NaN    23.599000   
25%             NaN  1965.75000  2.793664e+06       NaN    48.198000   
50%             NaN  1979.50000  7.023596e+06       NaN    60.712500   
75%             NaN  1993.25000  1.958522e+07       NaN    70.845500   
max             NaN  2007.00000  1.318683e+09       NaN    82.603000   

              gdp_cap  
count     1704.000000  
unique            NaN  
top               NaN  
freq              NaN  
mean      7215.327081  
std       9857.454543  
min        241.165876  
25%       1202.060309  
50%       3531.846988  
75%       9325.462346  
max     113523.132900

In [69]:
df["country"].value_counts()

Afghanistan          12
Pakistan             12
New Zealand          12
Nicaragua            12
Niger                12
                     ..
Eritrea              12
Equatorial Guinea    12
El Salvador          12
Egypt                12
Zimbabwe             12
Name: country, Length: 142, dtype: int64

In [72]:
df.value_counts("country")

country
Afghanistan          12
Pakistan             12
New Zealand          12
Nicaragua            12
Niger                12
                     ..
Eritrea              12
Equatorial Guinea    12
El Salvador          12
Egypt                12
Zimbabwe             12
Length: 142, dtype: int64

In [73]:
df.rename(columns={"country":"CountrY"})

CountrY  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [74]:
df.rename(columns={"country":"CountrY","year":"YeaR"})

CountrY  YeaR  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [75]:
df.rename({"country":"CountrY"},axis=1)

CountrY  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [76]:
df["new"]=df["gdp_cap"]/df["life_exp"]

In [77]:
df.head()

country  year  population continent  life_exp     gdp_cap        new
0  Afghanistan  1952     8425333      Asia    28.801  779.445314  27.063134
1  Afghanistan  1957     9240934      Asia    30.332  820.853030  27.062278
2  Afghanistan  1962    10267083      Asia    31.997  853.100710  26.661897
3  Afghanistan  1967    11537966      Asia    34.020  836.197138  24.579575
4  Afghanistan  1972    13079460      Asia    36.088  739.981106  20.504908

In [78]:
df.drop(columns=["new"])

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [79]:
df.head()

country  year  population continent  life_exp     gdp_cap        new
0  Afghanistan  1952     8425333      Asia    28.801  779.445314  27.063134
1  Afghanistan  1957     9240934      Asia    30.332  820.853030  27.062278
2  Afghanistan  1962    10267083      Asia    31.997  853.100710  26.661897
3  Afghanistan  1967    11537966      Asia    34.020  836.197138  24.579575
4  Afghanistan  1972    13079460      Asia    36.088  739.981106  20.504908

In [80]:
df.drop("new",axis=1)

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [81]:
ser=df["country"]
ser

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...     
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [82]:
ser[3]

'Afghanistan'

In [83]:
ser[3:7]

3    Afghanistan
4    Afghanistan
5    Afghanistan
6    Afghanistan
Name: country, dtype: object

In [84]:
ser.index

RangeIndex(start=0, stop=1704, step=1)

In [85]:
ser.index=[i for i in range(1,1705)]
ser

1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
5       Afghanistan
           ...     
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
1704       Zimbabwe
Name: country, Length: 1704, dtype: object

In [86]:
ser[1:4]

2    Afghanistan
3    Afghanistan
4    Afghanistan
Name: country, dtype: object

In [87]:
ser

1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
5       Afghanistan
           ...     
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
1704       Zimbabwe
Name: country, Length: 1704, dtype: object

In [88]:
df

country  year  population continent  life_exp     gdp_cap        new
0     Afghanistan  1952     8425333      Asia    28.801  779.445314  27.063134
1     Afghanistan  1957     9240934      Asia    30.332  820.853030  27.062278
2     Afghanistan  1962    10267083      Asia    31.997  853.100710  26.661897
3     Afghanistan  1967    11537966      Asia    34.020  836.197138  24.579575
4     Afghanistan  1972    13079460      Asia    36.088  739.981106  20.504908
...           ...   ...         ...       ...       ...         ...        ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306  11.325517
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786  11.484850
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960  16.929436
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623  16.805587
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298  10.801143

[1704 rows x 7 columns]

In [92]:
df.iloc[[0]]

country  year  population continent  life_exp     gdp_cap        new
0  Afghanistan  1952     8425333      Asia    28.801  779.445314  27.063134

In [93]:
df.loc[[0]]

country  year  population continent  life_exp     gdp_cap        new
0  Afghanistan  1952     8425333      Asia    28.801  779.445314  27.063134

In [94]:
df.set_index("country")

year  population continent  life_exp     gdp_cap        new
country                                                                 
Afghanistan  1952     8425333      Asia    28.801  779.445314  27.063134
Afghanistan  1957     9240934      Asia    30.332  820.853030  27.062278
Afghanistan  1962    10267083      Asia    31.997  853.100710  26.661897
Afghanistan  1967    11537966      Asia    34.020  836.197138  24.579575
Afghanistan  1972    13079460      Asia    36.088  739.981106  20.504908
...           ...         ...       ...       ...         ...        ...
Zimbabwe     1987     9216418    Africa    62.351  706.157306  11.325517
Zimbabwe     1992    10704340    Africa    60.377  693.420786  11.484850
Zimbabwe     1997    11404948    Africa    46.809  792.449960  16.929436
Zimbabwe     2002    11926563    Africa    39.989  672.038623  16.805587
Zimbabwe     2007    12311143    Africa    43.487  469.709298  10.801143

[1704 rows x 6 columns]

In [95]:
df.set_index("country",inplace=True)

In [96]:
df

year  population continent  life_exp     gdp_cap        new
country                                                                 
Afghanistan  1952     8425333      Asia    28.801  779.445314  27.063134
Afghanistan  1957     9240934      Asia    30.332  820.853030  27.062278
Afghanistan  1962    10267083      Asia    31.997  853.100710  26.661897
Afghanistan  1967    11537966      Asia    34.020  836.197138  24.579575
Afghanistan  1972    13079460      Asia    36.088  739.981106  20.504908
...           ...         ...       ...       ...         ...        ...
Zimbabwe     1987     9216418    Africa    62.351  706.157306  11.325517
Zimbabwe     1992    10704340    Africa    60.377  693.420786  11.484850
Zimbabwe     1997    11404948    Africa    46.809  792.449960  16.929436
Zimbabwe     2002    11926563    Africa    39.989  672.038623  16.805587
Zimbabwe     2007    12311143    Africa    43.487  469.709298  10.801143

[1704 rows x 6 columns]

In [97]:
df.loc["India"]

year  population continent  life_exp      gdp_cap        new
country                                                              
India    1952   372000000      Asia    37.373   546.565749  14.624615
India    1957   409000000      Asia    40.249   590.061996  14.660290
India    1962   454000000      Asia    43.605   658.347151  15.097974
India    1967   506000000      Asia    47.193   700.770611  14.849037
India    1972   567000000      Asia    50.651   724.032527  14.294536
India    1977   634000000      Asia    54.208   813.337323  15.004009
India    1982   708000000      Asia    56.596   855.723538  15.119859
India    1987   788000000      Asia    58.553   976.512676  16.677415
India    1992   872000000      Asia    60.223  1164.406809  19.334919
India    1997   959000000      Asia    61.765  1458.817442  23.618837
India    2002  1034172547      Asia    62.879  1746.769454  27.779854
India    2007  1110396331      Asia    64.698  2452.210407  37.902414

In [98]:
df.iloc["India"]

TypeError: Cannot index by location index with a non-integer key

In [99]:
df.reset_index()

country  year  population continent  life_exp     gdp_cap        new
0     Afghanistan  1952     8425333      Asia    28.801  779.445314  27.063134
1     Afghanistan  1957     9240934      Asia    30.332  820.853030  27.062278
2     Afghanistan  1962    10267083      Asia    31.997  853.100710  26.661897
3     Afghanistan  1967    11537966      Asia    34.020  836.197138  24.579575
4     Afghanistan  1972    13079460      Asia    36.088  739.981106  20.504908
...           ...   ...         ...       ...       ...         ...        ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306  11.325517
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786  11.484850
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960  16.929436
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623  16.805587
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298  10.801143

[1704 rows x 7 columns]

In [101]:
df.reset_index(inplace=True)

In [102]:
df

country  year  population continent  life_exp     gdp_cap        new
0     Afghanistan  1952     8425333      Asia    28.801  779.445314  27.063134
1     Afghanistan  1957     9240934      Asia    30.332  820.853030  27.062278
2     Afghanistan  1962    10267083      Asia    31.997  853.100710  26.661897
3     Afghanistan  1967    11537966      Asia    34.020  836.197138  24.579575
4     Afghanistan  1972    13079460      Asia    36.088  739.981106  20.504908
...           ...   ...         ...       ...       ...         ...        ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306  11.325517
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786  11.484850
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960  16.929436
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623  16.805587
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298  10.801143

[1704 rows x 7 columns]

In [103]:
df.index

RangeIndex(start=0, stop=1704, step=1)

In [104]:
df.index=[i for i in range(1,1705)]
df

country  year  population continent  life_exp     gdp_cap        new
1     Afghanistan  1952     8425333      Asia    28.801  779.445314  27.063134
2     Afghanistan  1957     9240934      Asia    30.332  820.853030  27.062278
3     Afghanistan  1962    10267083      Asia    31.997  853.100710  26.661897
4     Afghanistan  1967    11537966      Asia    34.020  836.197138  24.579575
5     Afghanistan  1972    13079460      Asia    36.088  739.981106  20.504908
...           ...   ...         ...       ...       ...         ...        ...
1700     Zimbabwe  1987     9216418    Africa    62.351  706.157306  11.325517
1701     Zimbabwe  1992    10704340    Africa    60.377  693.420786  11.484850
1702     Zimbabwe  1997    11404948    Africa    46.809  792.449960  16.929436
1703     Zimbabwe  2002    11926563    Africa    39.989  672.038623  16.805587
1704     Zimbabwe  2007    12311143    Africa    43.487  469.709298  10.801143

[1704 rows x 7 columns]

In [106]:
df.loc[[1]]

country  year  population continent  life_exp     gdp_cap        new
1  Afghanistan  1952     8425333      Asia    28.801  779.445314  27.063134

In [107]:
df.iloc[[1]]

country  year  population continent  life_exp    gdp_cap        new
2  Afghanistan  1957     9240934      Asia    30.332  820.85303  27.062278

In [108]:
df.index

Int64Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
            ...
            1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704],
           dtype='int64', length=1704)

In [111]:
df.loc[[2,3,5]]

country  year  population continent  life_exp     gdp_cap        new
2  Afghanistan  1957     9240934      Asia    30.332  820.853030  27.062278
3  Afghanistan  1962    10267083      Asia    31.997  853.100710  26.661897
5  Afghanistan  1972    13079460      Asia    36.088  739.981106  20.504908

In [112]:
df.loc[[2,3,7],["country"]]

country
2  Afghanistan
3  Afghanistan
7  Afghanistan

In [113]:
df.loc[[2,3,7],["country","year"]]

country  year
2  Afghanistan  1957
3  Afghanistan  1962
7  Afghanistan  1982

In [114]:
df.iloc[2:6,1:5]

year  population continent  life_exp
3  1962    10267083      Asia    31.997
4  1967    11537966      Asia    34.020
5  1972    13079460      Asia    36.088
6  1977    14880372      Asia    38.438

In [115]:
df.loc[2:7,"year":"life_exp"]

year  population continent  life_exp
2  1957     9240934      Asia    30.332
3  1962    10267083      Asia    31.997
4  1967    11537966      Asia    34.020
5  1972    13079460      Asia    36.088
6  1977    14880372      Asia    38.438
7  1982    12881816      Asia    39.854

In [116]:
df.iloc[1:4]

country  year  population continent  life_exp     gdp_cap        new
2  Afghanistan  1957     9240934      Asia    30.332  820.853030  27.062278
3  Afghanistan  1962    10267083      Asia    31.997  853.100710  26.661897
4  Afghanistan  1967    11537966      Asia    34.020  836.197138  24.579575

In [117]:
df.loc[1:4]

country  year  population continent  life_exp     gdp_cap        new
1  Afghanistan  1952     8425333      Asia    28.801  779.445314  27.063134
2  Afghanistan  1957     9240934      Asia    30.332  820.853030  27.062278
3  Afghanistan  1962    10267083      Asia    31.997  853.100710  26.661897
4  Afghanistan  1967    11537966      Asia    34.020  836.197138  24.579575

In [119]:
df.iloc[[1703,2,99],[4,5,3]]

life_exp     gdp_cap continent
1704    43.487  469.709298    Africa
3       31.997  853.100710      Asia
100     43.453  721.186086      Asia

In [121]:
df.iloc[-10:]

country  year  population continent  life_exp     gdp_cap        new
1695  Zimbabwe  1962     4277736    Africa    52.358  527.272182  10.070518
1696  Zimbabwe  1967     4995432    Africa    53.995  569.795071  10.552738
1697  Zimbabwe  1972     5861135    Africa    55.635  799.362176  14.367973
1698  Zimbabwe  1977     6642107    Africa    57.674  685.587682  11.887292
1699  Zimbabwe  1982     7636524    Africa    60.363  788.855041  13.068519
1700  Zimbabwe  1987     9216418    Africa    62.351  706.157306  11.325517
1701  Zimbabwe  1992    10704340    Africa    60.377  693.420786  11.484850
1702  Zimbabwe  1997    11404948    Africa    46.809  792.449960  16.929436
1703  Zimbabwe  2002    11926563    Africa    39.989  672.038623  16.805587
1704  Zimbabwe  2007    12311143    Africa    43.487  469.709298  10.801143

In [122]:
df.loc[2:20:2,"year":"gdp_cap":2]

year continent      gdp_cap
2   1957      Asia   820.853030
4   1967      Asia   836.197138
6   1977      Asia   786.113360
8   1987      Asia   852.395945
10  1997      Asia   635.341351
12  2007      Asia   974.580338
14  1957    Europe  1942.284244
16  1967    Europe  2760.196931
18  1977    Europe  3533.003910
20  1987    Europe  3738.932735

In [123]:
df.iloc[9:21:2,0:6:2]

country  population  life_exp
10  Afghanistan    22227415    41.763
12  Afghanistan    31889923    43.828
14      Albania     1476505    59.280
16      Albania     1984060    66.220
18      Albania     2509048    68.930
20      Albania     3075321    72.000

In [124]:
df

country  year  population continent  life_exp     gdp_cap        new
1     Afghanistan  1952     8425333      Asia    28.801  779.445314  27.063134
2     Afghanistan  1957     9240934      Asia    30.332  820.853030  27.062278
3     Afghanistan  1962    10267083      Asia    31.997  853.100710  26.661897
4     Afghanistan  1967    11537966      Asia    34.020  836.197138  24.579575
5     Afghanistan  1972    13079460      Asia    36.088  739.981106  20.504908
...           ...   ...         ...       ...       ...         ...        ...
1700     Zimbabwe  1987     9216418    Africa    62.351  706.157306  11.325517
1701     Zimbabwe  1992    10704340    Africa    60.377  693.420786  11.484850
1702     Zimbabwe  1997    11404948    Africa    46.809  792.449960  16.929436
1703     Zimbabwe  2002    11926563    Africa    39.989  672.038623  16.805587
1704     Zimbabwe  2007    12311143    Africa    43.487  469.709298  10.801143

[1704 rows x 7 columns]

In [126]:
df.iloc[29:40]

country  year  population continent  life_exp      gdp_cap         new
30  Algeria  1977    17152804    Africa    58.014  4910.416756   84.641927
31  Algeria  1982    20033753    Africa    61.368  5745.160213   93.618176
32  Algeria  1987    23254956    Africa    65.799  5681.358539   86.344147
33  Algeria  1992    26298373    Africa    67.744  5023.216647   74.149986
34  Algeria  1997    29072015    Africa    69.152  4797.295051   69.373193
35  Algeria  2002    31287142    Africa    70.994  5288.040382   74.485737
36  Algeria  2007    33333216    Africa    72.301  6223.367465   86.075815
37   Angola  1952     4232095    Africa    30.015  3520.610273  117.295028
38   Angola  1957     4561361    Africa    31.999  3827.940465  119.626878
39   Angola  1962     4826015    Africa    34.000  4269.276742  125.566963
40   Angola  1967     5247469    Africa    35.985  5522.776375  153.474403

In [127]:
dic={"country":"Hola",
    "year":2022,
    "population":99,
    "continent":"Ana",
    "life_exp":22,
    "gdp_cap":11}

In [129]:
df=df.append(dic)
df

/var/folders/t2/3z1ygvv95h72q7ygpfjbdsgr0000gn/T/ipykernel_1343/3927593697.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(dic)


TypeError: Can only append a dict if ignore_index=True

In [130]:
df=df.append(dic,ignore_index=True)
df

/var/folders/t2/3z1ygvv95h72q7ygpfjbdsgr0000gn/T/ipykernel_1343/2648487230.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(dic,ignore_index=True)


country  year  population continent  life_exp     gdp_cap        new
0     Afghanistan  1952     8425333      Asia    28.801  779.445314  27.063134
1     Afghanistan  1957     9240934      Asia    30.332  820.853030  27.062278
2     Afghanistan  1962    10267083      Asia    31.997  853.100710  26.661897
3     Afghanistan  1967    11537966      Asia    34.020  836.197138  24.579575
4     Afghanistan  1972    13079460      Asia    36.088  739.981106  20.504908
...           ...   ...         ...       ...       ...         ...        ...
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786  11.484850
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960  16.929436
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623  16.805587
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298  10.801143
1704         Hola  2022          99       Ana    22.000   11.000000        NaN

[1705 rows x 7 columns]

In [131]:
len(df.index)

1705

In [133]:
df.loc[len(df.index)]=["India",2023,100,"Asia",11,20,111]
df

country  year  population continent  life_exp     gdp_cap  \
0     Afghanistan  1952     8425333      Asia    28.801  779.445314   
1     Afghanistan  1957     9240934      Asia    30.332  820.853030   
2     Afghanistan  1962    10267083      Asia    31.997  853.100710   
3     Afghanistan  1967    11537966      Asia    34.020  836.197138   
4     Afghanistan  1972    13079460      Asia    36.088  739.981106   
...           ...   ...         ...       ...       ...         ...   
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960   
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623   
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298   
1704         Hola  2022          99       Ana    22.000   11.000000   
1705        India  2023         100      Asia    11.000   20.000000   

             new  
0      27.063134  
1      27.062278  
2      26.661897  
3      24.579575  
4      20.504908  
...          ...  
1701   16.929436  
1702   16.805587  
1703   10.801143  
1704         NaN  
1705  111.000000  

[1706 rows x 7 columns]

In [137]:
len(df.index)

1706

12930

In [138]:
df

country  year  population continent  life_exp     gdp_cap  \
0     Afghanistan  1952     8425333      Asia    28.801  779.445314   
1     Afghanistan  1957     9240934      Asia    30.332  820.853030   
2     Afghanistan  1962    10267083      Asia    31.997  853.100710   
3     Afghanistan  1967    11537966      Asia    34.020  836.197138   
4     Afghanistan  1972    13079460      Asia    36.088  739.981106   
...           ...   ...         ...       ...       ...         ...   
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960   
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623   
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298   
1704         Hola  2022          99       Ana    22.000   11.000000   
1705        India  2023         100      Asia    11.000   20.000000   

             new  
0      27.063134  
1      27.062278  
2      26.661897  
3      24.579575  
4      20.504908  
...          ...  
1701   16.929436  
1702   16.805587  
1703   10.801143  
1704         NaN  
1705  111.000000  

[1706 rows x 7 columns]

In [139]:
df["life_exp"].sum()

101377.44467999999

In [140]:
df["life_exp"].mean()

59.42405901524029

In [141]:
df["life_exp"].max()

82.603

In [142]:
df["life_exp"].min()

11.0

In [143]:
df["life_exp"].count()

1706

In [144]:
df_ypl=df[["year","population","life_exp"]]
df_ypl

year  population  life_exp
0     1952     8425333    28.801
1     1957     9240934    30.332
2     1962    10267083    31.997
3     1967    11537966    34.020
4     1972    13079460    36.088
...    ...         ...       ...
1701  1997    11404948    46.809
1702  2002    11926563    39.989
1703  2007    12311143    43.487
1704  2022          99    22.000
1705  2023         100    11.000

[1706 rows x 3 columns]

In [146]:
df.sort_values(["year"])

country  year  population continent  life_exp       gdp_cap  \
0          Afghanistan  1952     8425333      Asia    28.801    779.445314   
552             Gambia  1952      284320    Africa    30.000    485.230659   
564            Germany  1952    69145952    Europe    67.500   7144.114393   
576              Ghana  1952     5581001    Africa    43.149    911.298937   
588             Greece  1952     7733250    Europe    65.860   3530.690067   
...                ...   ...         ...       ...       ...           ...   
71           Australia  2007    20434176   Oceania    81.235  34435.367440   
839   Korea, Dem. Rep.  2007    23301725      Asia    67.297   1593.065480   
911              Libya  2007     6036914    Africa    73.952  12057.499280   
1704              Hola  2022          99       Ana    22.000     11.000000   
1705             India  2023         100      Asia    11.000     20.000000   

             new  
0      27.063134  
552    16.174355  
564   105.838732  
576    21.119816  
588    53.609020  
...          ...  
71    423.898165  
839    23.672162  
911   163.044938  
1704         NaN  
1705  111.000000  

[1706 rows x 7 columns]

In [150]:
df.sort_values(["year"],ascending=True)

country  year  population continent  life_exp       gdp_cap  \
0          Afghanistan  1952     8425333      Asia    28.801    779.445314   
552             Gambia  1952      284320    Africa    30.000    485.230659   
564            Germany  1952    69145952    Europe    67.500   7144.114393   
576              Ghana  1952     5581001    Africa    43.149    911.298937   
588             Greece  1952     7733250    Europe    65.860   3530.690067   
...                ...   ...         ...       ...       ...           ...   
71           Australia  2007    20434176   Oceania    81.235  34435.367440   
839   Korea, Dem. Rep.  2007    23301725      Asia    67.297   1593.065480   
911              Libya  2007     6036914    Africa    73.952  12057.499280   
1704              Hola  2022          99       Ana    22.000     11.000000   
1705             India  2023         100      Asia    11.000     20.000000   

             new  
0      27.063134  
552    16.174355  
564   105.838732  
576    21.119816  
588    53.609020  
...          ...  
71    423.898165  
839    23.672162  
911   163.044938  
1704         NaN  
1705  111.000000  

[1706 rows x 7 columns]

In [151]:
df.sort_values(["year"],ascending=False)

country  year  population continent  life_exp       gdp_cap  \
1705           India  2023         100      Asia    11.000     20.000000   
1704            Hola  2022          99       Ana    22.000     11.000000   
1523        Tanzania  2007    38139640    Africa    52.517   1107.482182   
755          Ireland  2007     4109086    Europe    78.885  40675.996350   
1451           Sudan  2007    42292929    Africa    58.556   2602.394995   
...              ...   ...         ...       ...       ...           ...   
612           Guinea  1952     2664249    Africa    33.609    510.196492   
1596  United Kingdom  1952    50430000    Europe    69.180   9979.508487   
1164        Pakistan  1952    41346560      Asia    43.436    684.597144   
600        Guatemala  1952     3146381  Americas    42.023   2428.237769   
0        Afghanistan  1952     8425333      Asia    28.801    779.445314   

             new  
1705  111.000000  
1704         NaN  
1523   21.088070  
755   515.636640  
1451   44.442841  
...          ...  
612    15.180353  
1596  144.254242  
1164   15.761054  
600    57.783542  
0      27.063134  

[1706 rows x 7 columns]

In [152]:
df.sort_values(["year","life_exp"],ascending=False)

country  year  population continent  life_exp       gdp_cap  \
1705             India  2023         100      Asia    11.000     20.000000   
1704              Hola  2022          99       Ana    22.000     11.000000   
803              Japan  2007   127467972      Asia    82.603  31656.068060   
671   Hong Kong, China  2007     6980412      Asia    82.208  39724.978670   
695            Iceland  2007      301931    Europe    81.757  36180.789190   
...                ...   ...         ...       ...       ...           ...   
1032        Mozambique  1952     6446316    Africa    31.286    468.526038   
1344      Sierra Leone  1952     2143249    Africa    30.331    879.787736   
36              Angola  1952     4232095    Africa    30.015   3520.610273   
552             Gambia  1952      284320    Africa    30.000    485.230659   
0          Afghanistan  1952     8425333      Asia    28.801    779.445314   

             new  
1705  111.000000  
1704         NaN  
803   383.231457  
671   483.225217  
695   442.540568  
...          ...  
1032   14.975581  
1344   29.006223  
36    117.295028  
552    16.174355  
0      27.063134  

[1706 rows x 7 columns]

In [153]:
df.sort_values?

In [155]:
df.sort_values(["year"]).head(10)

country  year  population continent  life_exp      gdp_cap  \
0      Afghanistan  1952     8425333      Asia    28.801   779.445314   
552         Gambia  1952      284320    Africa    30.000   485.230659   
564        Germany  1952    69145952    Europe    67.500  7144.114393   
576          Ghana  1952     5581001    Africa    43.149   911.298937   
588         Greece  1952     7733250    Europe    65.860  3530.690067   
600      Guatemala  1952     3146381  Americas    42.023  2428.237769   
612         Guinea  1952     2664249    Africa    33.609   510.196492   
624  Guinea-Bissau  1952      580653    Africa    32.500   299.850319   
636          Haiti  1952     3201488  Americas    37.579  1840.366939   
648       Honduras  1952     1517453  Americas    41.912  2194.926204   

            new  
0     27.063134  
552   16.174355  
564  105.838732  
576   21.119816  
588   53.609020  
600   57.783542  
612   15.180353  
624    9.226164  
636   48.973281  
648   52.369875