In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5]

In [3]:
a

[1, 2, 3, 4, 5]

In [4]:
type(a)

list

In [5]:
b=[i**2 for i in a]
b

[1, 4, 9, 16, 25]

In [6]:
aa=np.array([1,2,3,4,5])
aa

array([1, 2, 3, 4, 5])

In [7]:
type(aa)

numpy.ndarray

In [9]:
aa**2

array([ 1,  4,  9, 16, 25])

In [10]:
aa.shape

(5,)

In [11]:
aa.size

5

In [12]:
aa.ndim

1

In [13]:
len(aa)

5

In [14]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [18]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [19]:
a=np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
a[3]

4

In [21]:
a[-5]

4

In [22]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
a[2,3]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [24]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
a[[2,4,6]]

array([3, 5, 7])

In [26]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
a[3:5]

array([4, 5])

In [28]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
a<5

array([ True,  True,  True,  True, False, False, False, False])

In [30]:
a[a<5]

array([1, 2, 3, 4])

In [31]:
a.max()

8

In [32]:
np.max(a)

8

In [33]:
a.min()

1

In [34]:
np.min(a)

1

In [35]:
a.sum()

36

In [36]:
np.sum(a)

36

In [37]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
a.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
a.shape

(8,)